### ISSUE TITLE
An error occurred while creating the topic model

### ISSUE THREAD

**Issue by monajalal** [davidatbu/openFraming#279]
<img width="1270" alt="Screen Shot 2020-07-13 at 11 37 22 AM" src="https://user-images.githubusercontent.com/1892917/87323867-57618400-c4fd-11ea-9447-2e9ae1730520.png">

*Also after we upload the test.csv it shouldn't be shown in red.

**Comment by davidatbu** [comment]
Hi @monajalal , until we start echoing back to the user the error messages the backend gives, I don't think we should concern ourselves with such error messages, because we have no idea what the backend actually said. I vote for closing this until we get the frontend to echo back to the user the error messages the backend gives( #293 )

**Comment by davidatbu** [comment]
Can we close this, for the reason that I mentioned above?
