### ISSUE TITLE
What are the minimum system specs required for AWS EC2 instance? Then Downgrade to it.

### ISSUE THREAD

**Issue by monajalal** [davidatbu/openFraming#299]
RAM: ?
HDD/SSD:?

Currently trying to decide if would be okay to downgrade from p3.2xlarge to p2.xlarge would be feasible for us or not?

(p3.2xlarge) would cost us 3*24*60= $4320 for duration of two months
(p2.xlarge) would cost us 0.9*24*60=$1296 for duration of two months

Currently, running on a p3.2xlarge EC2 instance:
<img width="1197" alt="Screen Shot 2020-07-14 at 12 12 30 PM" src="https://user-images.githubusercontent.com/1892917/87473711-e6e75f80-c5ef-11ea-9bd8-8ba36c1c9409.png">

**Comment by davidatbu** [comment]
Hi @monajalal ,

> RAM: ?
> HDD/SSD:?

  I am not sure what would be ideal for our case. I think it will only become clear after we look at the usage profile on the AWS console after a week or two.

> Currently trying to decide if would be okay to downgrade from p3.2xlarge to p2.xlarge would be feasible for us or not?

Like I said in the email, I think running the web server on a GPU instance is too expensive. I think we should focus on making the system asynchronous(#301 ) so that the user doesnt have to keep their tab open. 

If necessary, in the future, there's also the possibility of modifying the code such that we spin up a separate GPU instance to handle the jobs for a very limited time. But I think that's a stretch goal, one we can reach for, in the future, after we deal with more pertinent issues.

**Comment by davidatbu** [comment]
Closing since we reached a decision yesterday.
